version: '3'

services:
  todo:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo:latest
    container_name: todo
    ports: 
      - "80:8000"
    volumes:
      - .:/usr/src/todo/
    command: python manage.py runserver 0.0.0.0:8000