# Generated by Django 5.0.4 on 2024-05-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user_alter_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('doing', 'doing'), ('done', 'done')], max_length=5),
        ),
    ]
